package com.tvt.fdlq.mapper;

import com.tvt.fdlq.domain.RoomConfig;
import com.tvt.fdlq.domain.RoomConfigExample;
import java.util.List;

public interface RoomConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomconfig
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomconfig
     *
     * @mbg.generated
     */
    int insert(RoomConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomconfig
     *
     * @mbg.generated
     */
    int insertSelective(RoomConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomconfig
     *
     * @mbg.generated
     */
    List<RoomConfig> selectByExample(RoomConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomconfig
     *
     * @mbg.generated
     */
    RoomConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomconfig
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoomConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomconfig
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoomConfig record);
}