package com.tvt.fdlq.domain;

public class RoomConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomconfig.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomconfig.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomconfig.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomconfig.id
     *
     * @return the value of roomconfig.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomconfig.id
     *
     * @param id the value for roomconfig.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomconfig.name
     *
     * @return the value of roomconfig.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomconfig.name
     *
     * @param name the value for roomconfig.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomconfig.type
     *
     * @return the value of roomconfig.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomconfig.type
     *
     * @param type the value for roomconfig.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}