package com.tvt.fdlq.domain;

public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomType1
     *
     * @mbg.generated
     */
    private Integer roomtype1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomType2
     *
     * @mbg.generated
     */
    private Integer roomtype2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomType3
     *
     * @mbg.generated
     */
    private Integer roomtype3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.area
     *
     * @mbg.generated
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.monthRent
     *
     * @mbg.generated
     */
    private Integer monthrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.rentPeriod1
     *
     * @mbg.generated
     */
    private Integer rentperiod1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.rentPeriod2
     *
     * @mbg.generated
     */
    private Integer rentperiod2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.config
     *
     * @mbg.generated
     */
    private String config;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.pid
     *
     * @return the value of room.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.pid
     *
     * @param pid the value for room.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.name
     *
     * @return the value of room.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.name
     *
     * @param name the value for room.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomType1
     *
     * @return the value of room.roomType1
     *
     * @mbg.generated
     */
    public Integer getRoomtype1() {
        return roomtype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomType1
     *
     * @param roomtype1 the value for room.roomType1
     *
     * @mbg.generated
     */
    public void setRoomtype1(Integer roomtype1) {
        this.roomtype1 = roomtype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomType2
     *
     * @return the value of room.roomType2
     *
     * @mbg.generated
     */
    public Integer getRoomtype2() {
        return roomtype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomType2
     *
     * @param roomtype2 the value for room.roomType2
     *
     * @mbg.generated
     */
    public void setRoomtype2(Integer roomtype2) {
        this.roomtype2 = roomtype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomType3
     *
     * @return the value of room.roomType3
     *
     * @mbg.generated
     */
    public Integer getRoomtype3() {
        return roomtype3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomType3
     *
     * @param roomtype3 the value for room.roomType3
     *
     * @mbg.generated
     */
    public void setRoomtype3(Integer roomtype3) {
        this.roomtype3 = roomtype3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.level
     *
     * @return the value of room.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.level
     *
     * @param level the value for room.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.area
     *
     * @return the value of room.area
     *
     * @mbg.generated
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.area
     *
     * @param area the value for room.area
     *
     * @mbg.generated
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.monthRent
     *
     * @return the value of room.monthRent
     *
     * @mbg.generated
     */
    public Integer getMonthrent() {
        return monthrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.monthRent
     *
     * @param monthrent the value for room.monthRent
     *
     * @mbg.generated
     */
    public void setMonthrent(Integer monthrent) {
        this.monthrent = monthrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.rentPeriod1
     *
     * @return the value of room.rentPeriod1
     *
     * @mbg.generated
     */
    public Integer getRentperiod1() {
        return rentperiod1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.rentPeriod1
     *
     * @param rentperiod1 the value for room.rentPeriod1
     *
     * @mbg.generated
     */
    public void setRentperiod1(Integer rentperiod1) {
        this.rentperiod1 = rentperiod1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.rentPeriod2
     *
     * @return the value of room.rentPeriod2
     *
     * @mbg.generated
     */
    public Integer getRentperiod2() {
        return rentperiod2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.rentPeriod2
     *
     * @param rentperiod2 the value for room.rentPeriod2
     *
     * @mbg.generated
     */
    public void setRentperiod2(Integer rentperiod2) {
        this.rentperiod2 = rentperiod2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.config
     *
     * @return the value of room.config
     *
     * @mbg.generated
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.config
     *
     * @param config the value for room.config
     *
     * @mbg.generated
     */
    public void setConfig(String config) {
        this.config = config == null ? null : config.trim();
    }
}