package com.tvt.fdlq.domain;

import java.util.ArrayList;
import java.util.List;

public class RoomExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    public RoomExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andRoomtype1IsNull() {
            addCriterion("roomType1 is null");
            return (Criteria) this;
        }

        public Criteria andRoomtype1IsNotNull() {
            addCriterion("roomType1 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomtype1EqualTo(Integer value) {
            addCriterion("roomType1 =", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1NotEqualTo(Integer value) {
            addCriterion("roomType1 <>", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1GreaterThan(Integer value) {
            addCriterion("roomType1 >", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1GreaterThanOrEqualTo(Integer value) {
            addCriterion("roomType1 >=", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1LessThan(Integer value) {
            addCriterion("roomType1 <", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1LessThanOrEqualTo(Integer value) {
            addCriterion("roomType1 <=", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1In(List<Integer> values) {
            addCriterion("roomType1 in", values, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1NotIn(List<Integer> values) {
            addCriterion("roomType1 not in", values, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1Between(Integer value1, Integer value2) {
            addCriterion("roomType1 between", value1, value2, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1NotBetween(Integer value1, Integer value2) {
            addCriterion("roomType1 not between", value1, value2, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype2IsNull() {
            addCriterion("roomType2 is null");
            return (Criteria) this;
        }

        public Criteria andRoomtype2IsNotNull() {
            addCriterion("roomType2 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomtype2EqualTo(Integer value) {
            addCriterion("roomType2 =", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2NotEqualTo(Integer value) {
            addCriterion("roomType2 <>", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2GreaterThan(Integer value) {
            addCriterion("roomType2 >", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2GreaterThanOrEqualTo(Integer value) {
            addCriterion("roomType2 >=", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2LessThan(Integer value) {
            addCriterion("roomType2 <", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2LessThanOrEqualTo(Integer value) {
            addCriterion("roomType2 <=", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2In(List<Integer> values) {
            addCriterion("roomType2 in", values, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2NotIn(List<Integer> values) {
            addCriterion("roomType2 not in", values, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2Between(Integer value1, Integer value2) {
            addCriterion("roomType2 between", value1, value2, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2NotBetween(Integer value1, Integer value2) {
            addCriterion("roomType2 not between", value1, value2, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype3IsNull() {
            addCriterion("roomType3 is null");
            return (Criteria) this;
        }

        public Criteria andRoomtype3IsNotNull() {
            addCriterion("roomType3 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomtype3EqualTo(Integer value) {
            addCriterion("roomType3 =", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3NotEqualTo(Integer value) {
            addCriterion("roomType3 <>", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3GreaterThan(Integer value) {
            addCriterion("roomType3 >", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3GreaterThanOrEqualTo(Integer value) {
            addCriterion("roomType3 >=", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3LessThan(Integer value) {
            addCriterion("roomType3 <", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3LessThanOrEqualTo(Integer value) {
            addCriterion("roomType3 <=", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3In(List<Integer> values) {
            addCriterion("roomType3 in", values, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3NotIn(List<Integer> values) {
            addCriterion("roomType3 not in", values, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3Between(Integer value1, Integer value2) {
            addCriterion("roomType3 between", value1, value2, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3NotBetween(Integer value1, Integer value2) {
            addCriterion("roomType3 not between", value1, value2, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(Integer value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(Integer value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(Integer value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(Integer value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(Integer value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(Integer value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<Integer> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<Integer> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(Integer value1, Integer value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(Integer value1, Integer value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andMonthrentIsNull() {
            addCriterion("monthRent is null");
            return (Criteria) this;
        }

        public Criteria andMonthrentIsNotNull() {
            addCriterion("monthRent is not null");
            return (Criteria) this;
        }

        public Criteria andMonthrentEqualTo(Integer value) {
            addCriterion("monthRent =", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentNotEqualTo(Integer value) {
            addCriterion("monthRent <>", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentGreaterThan(Integer value) {
            addCriterion("monthRent >", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentGreaterThanOrEqualTo(Integer value) {
            addCriterion("monthRent >=", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentLessThan(Integer value) {
            addCriterion("monthRent <", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentLessThanOrEqualTo(Integer value) {
            addCriterion("monthRent <=", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentIn(List<Integer> values) {
            addCriterion("monthRent in", values, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentNotIn(List<Integer> values) {
            addCriterion("monthRent not in", values, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentBetween(Integer value1, Integer value2) {
            addCriterion("monthRent between", value1, value2, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentNotBetween(Integer value1, Integer value2) {
            addCriterion("monthRent not between", value1, value2, "monthrent");
            return (Criteria) this;
        }

        public Criteria andRentperiod1IsNull() {
            addCriterion("rentPeriod1 is null");
            return (Criteria) this;
        }

        public Criteria andRentperiod1IsNotNull() {
            addCriterion("rentPeriod1 is not null");
            return (Criteria) this;
        }

        public Criteria andRentperiod1EqualTo(Integer value) {
            addCriterion("rentPeriod1 =", value, "rentperiod1");
            return (Criteria) this;
        }

        public Criteria andRentperiod1NotEqualTo(Integer value) {
            addCriterion("rentPeriod1 <>", value, "rentperiod1");
            return (Criteria) this;
        }

        public Criteria andRentperiod1GreaterThan(Integer value) {
            addCriterion("rentPeriod1 >", value, "rentperiod1");
            return (Criteria) this;
        }

        public Criteria andRentperiod1GreaterThanOrEqualTo(Integer value) {
            addCriterion("rentPeriod1 >=", value, "rentperiod1");
            return (Criteria) this;
        }

        public Criteria andRentperiod1LessThan(Integer value) {
            addCriterion("rentPeriod1 <", value, "rentperiod1");
            return (Criteria) this;
        }

        public Criteria andRentperiod1LessThanOrEqualTo(Integer value) {
            addCriterion("rentPeriod1 <=", value, "rentperiod1");
            return (Criteria) this;
        }

        public Criteria andRentperiod1In(List<Integer> values) {
            addCriterion("rentPeriod1 in", values, "rentperiod1");
            return (Criteria) this;
        }

        public Criteria andRentperiod1NotIn(List<Integer> values) {
            addCriterion("rentPeriod1 not in", values, "rentperiod1");
            return (Criteria) this;
        }

        public Criteria andRentperiod1Between(Integer value1, Integer value2) {
            addCriterion("rentPeriod1 between", value1, value2, "rentperiod1");
            return (Criteria) this;
        }

        public Criteria andRentperiod1NotBetween(Integer value1, Integer value2) {
            addCriterion("rentPeriod1 not between", value1, value2, "rentperiod1");
            return (Criteria) this;
        }

        public Criteria andRentperiod2IsNull() {
            addCriterion("rentPeriod2 is null");
            return (Criteria) this;
        }

        public Criteria andRentperiod2IsNotNull() {
            addCriterion("rentPeriod2 is not null");
            return (Criteria) this;
        }

        public Criteria andRentperiod2EqualTo(Integer value) {
            addCriterion("rentPeriod2 =", value, "rentperiod2");
            return (Criteria) this;
        }

        public Criteria andRentperiod2NotEqualTo(Integer value) {
            addCriterion("rentPeriod2 <>", value, "rentperiod2");
            return (Criteria) this;
        }

        public Criteria andRentperiod2GreaterThan(Integer value) {
            addCriterion("rentPeriod2 >", value, "rentperiod2");
            return (Criteria) this;
        }

        public Criteria andRentperiod2GreaterThanOrEqualTo(Integer value) {
            addCriterion("rentPeriod2 >=", value, "rentperiod2");
            return (Criteria) this;
        }

        public Criteria andRentperiod2LessThan(Integer value) {
            addCriterion("rentPeriod2 <", value, "rentperiod2");
            return (Criteria) this;
        }

        public Criteria andRentperiod2LessThanOrEqualTo(Integer value) {
            addCriterion("rentPeriod2 <=", value, "rentperiod2");
            return (Criteria) this;
        }

        public Criteria andRentperiod2In(List<Integer> values) {
            addCriterion("rentPeriod2 in", values, "rentperiod2");
            return (Criteria) this;
        }

        public Criteria andRentperiod2NotIn(List<Integer> values) {
            addCriterion("rentPeriod2 not in", values, "rentperiod2");
            return (Criteria) this;
        }

        public Criteria andRentperiod2Between(Integer value1, Integer value2) {
            addCriterion("rentPeriod2 between", value1, value2, "rentperiod2");
            return (Criteria) this;
        }

        public Criteria andRentperiod2NotBetween(Integer value1, Integer value2) {
            addCriterion("rentPeriod2 not between", value1, value2, "rentperiod2");
            return (Criteria) this;
        }

        public Criteria andConfigIsNull() {
            addCriterion("config is null");
            return (Criteria) this;
        }

        public Criteria andConfigIsNotNull() {
            addCriterion("config is not null");
            return (Criteria) this;
        }

        public Criteria andConfigEqualTo(String value) {
            addCriterion("config =", value, "config");
            return (Criteria) this;
        }

        public Criteria andConfigNotEqualTo(String value) {
            addCriterion("config <>", value, "config");
            return (Criteria) this;
        }

        public Criteria andConfigGreaterThan(String value) {
            addCriterion("config >", value, "config");
            return (Criteria) this;
        }

        public Criteria andConfigGreaterThanOrEqualTo(String value) {
            addCriterion("config >=", value, "config");
            return (Criteria) this;
        }

        public Criteria andConfigLessThan(String value) {
            addCriterion("config <", value, "config");
            return (Criteria) this;
        }

        public Criteria andConfigLessThanOrEqualTo(String value) {
            addCriterion("config <=", value, "config");
            return (Criteria) this;
        }

        public Criteria andConfigLike(String value) {
            addCriterion("config like", value, "config");
            return (Criteria) this;
        }

        public Criteria andConfigNotLike(String value) {
            addCriterion("config not like", value, "config");
            return (Criteria) this;
        }

        public Criteria andConfigIn(List<String> values) {
            addCriterion("config in", values, "config");
            return (Criteria) this;
        }

        public Criteria andConfigNotIn(List<String> values) {
            addCriterion("config not in", values, "config");
            return (Criteria) this;
        }

        public Criteria andConfigBetween(String value1, String value2) {
            addCriterion("config between", value1, value2, "config");
            return (Criteria) this;
        }

        public Criteria andConfigNotBetween(String value1, String value2) {
            addCriterion("config not between", value1, value2, "config");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}